
server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        #git 远程仓库
        git:
          uri: https://github.com/qinqinwodetao/config-files.git
          username: qinqinwodetao
          password: wcy968968

eureka:
  client:
    serviceUrl:
      defaultZone: http://cluster1:8761/eureka/
  instance:
    hostname: microservice-config-server
    prefer-ip-address: true
    secure-virtual-host-name: microservice-config-server
security:
  basic:
    enabled: false
  user:
    name: root
    password: 123456
