
server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        #git ≤÷ø‚µÿ÷∑≈‰÷√
        git:
          uri: https://github.com/qinqinwodetao/config-files.git
          username: qinqinwodetao
          password: wcy968968



