server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: eurekaClient         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
spring:
  application:
    name: wucyEurekaServer