jedis:
    ip: 127.0.0.1
    port: 6379

server:
  port: 6004

eureka:
  client:
    serviceUrl:
      defaultZone: http://cluster1:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level: debug

spring:
  application:
    name: microservice-gateway-zuul-aggregation



info:
  app:
  name: microservice-gateway-zuul-aggregation
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@
  spring:
    source: @spring.version@
    target: @spring.version@
