server:
  port: 8081
info:
  app:
  name: microservice-config-client
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@
  spring:
    source: @spring.version@
    target: @spring.version@
logging:
  level: debug



